defaultNamespace: fleet-argocd-example
helm:
  chart: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: 5.51.6  # Optional: replace with desired version  
targetCustomizations:
- name: dev
  helm:
    values:
      replication: false
  clusterSelector:
    matchLabels:
      env: dev

- name: prod
  helm:
    values:
      serviceType: NodePort
      replicas: 3
  clusterSelector:
    matchLabels:
      env: prod